version: '3.8'

services:
  mcp-proxy:
    build: .
    container_name: mcp-proxy-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_CONCURRENT_REQUESTS=50
      - REQUEST_TIMEOUT=35000
      - CONNECTION_TIMEOUT=8000
      - RETRY_ATTEMPTS=3
      - RETRY_DELAY=500
      - MAX_RETRY_DELAY=3000
      - CACHE_ENABLED=true
      - CACHE_TTL_INITIALIZE=600
      - CACHE_TTL_TOOLS_LIST=300
      - CIRCUIT_BREAKER_ENABLED=true
      - CIRCUIT_BREAKER_THRESHOLD=5
      - CIRCUIT_BREAKER_TIMEOUT=30000
      - DIFY_BASE_URL=http://dify.ireborn.com.cn
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge
